### ISSUE TITLE
How do I scan for missing poster/cover?

### ISSUE THREAD

**Issue by chilman408** [JavLuv/JavLuv#138]
I moved a few files around in the database but forgot to move the associated cover art?  Do I have to delete the nfo file and redo the scan to get a cover art?

**Comment by JavLuv** [comment]
If the cover are is in the same folder and has the movie ID in it's filename, you should be able to just right-click and re-scan files.  Otherwise, check Advanced Options in settings, and in the missing thumbnail view, you should be able to right-click on movie thumbnail and Import Cover Image.

**Comment by chilman408** [comment]
Thx, if I delete the nfo file, would it initiate a rescan?  Or how would I trigger an auto pull of cover art at this point?

**Comment by JavLuv** [comment]
You can so the same thing by selecting Advanced options in settings, right click on a thumbnail and selecting Regenerate metadata.  It basically deletes the nfo and rescans.  That should download a cover if needed.
