### ISSUE TITLE
Organize covers and metadata files suggestion

### ISSUE THREAD

**Issue by karizzzan** [JavLuv/JavLuv#160]
Hey, there is one feature that is holding me back from using the program regularly and that is how much it clutters my folders with .nfo and .jpg files. I feel like it should use a better storage system to not only lessen the number of files in each directory (Explorer struggles with all these files and makes browsing difficult), but will also allow backups to be easily used?

I realize this might have to do with kodi, but perhaps give us the option to store it in AppData or the like for those who prefer it this way?

Thanks

**Comment by JavLuv** [comment]
This was actually the first feature request in the list: [](https://github.com/JavLuv/JavLuv/issues/1)

I'm not sure when I'll be able to get to this, as I haven't had a lot of free time to work on it.  Maybe someday though?
