### ISSUE TITLE
parathd movie id are not handled and are truncated

### ISSUE THREAD

**Issue by billz2** [JavLuv/JavLuv#81]
wonderful browser, did notice that codes for paradise tv are not handled probably because they are over 6 characters, for example parathd-2281 gets processed as apartdh-2281 therefore not finding movie info. The old codes such as parat-533 work fine.

**Comment by JavLuv** [comment]
Yeah, 6 characters was assumed to be the limit for codes.  I'll bump that up to 7 characters.

**Comment by billz2** [comment]
> Yeah, 6 characters was assumed to be the limit for codes. I'll bump that up to 7 characters.

many thanks
