### ISSUE TITLE
When more than 1 cover image is downloaded, only 1 of them is moved with auto move

### ISSUE THREAD

**Issue by karad716** [JavLuv/JavLuv#92]
Some movies download both the jpg and webp format of the cover image. With auto move enabled, only the webp image is moved while jpg remains in the original download folder. Personally, I think just 1 image should be downloaded for each movie in the first place, preferably jpg to be consistent.

**Comment by JavLuv** [comment]
JavLuv downloads multiple cover images to make sure that it obtains the highest resolution cover available among the sites scraped.  Some sites host webp images now, so I don't want to exclude those if they're the best quality, or even the only cover image available.  

However, JavLuv is not supposed to leave extra movies behind like that.  I'll look into why that's happening.

**Comment by JavLuv** [comment]
Fixed in develop branch, and will be merged to main for next release.  Thanks for the report.
