### ISSUE TITLE
Option to change actress name order to last name then first name

### ISSUE THREAD

**Issue by karad716** [JavLuv/JavLuv#93]
Would be nice for actress view and auto move just because it's what I'm used to

**Comment by JavLuv** [comment]
Agreed.  I've been putting this off until someone requested it though.

**Comment by hermit3dpurple** [comment]
I'd love that option too. I see it's been a while since anyone mentioned it. I just began using JavLuv and I... luv it. With that option, it would be close to perfection.  With an added option to state on what disk we stored this or that film, it would get even closer :D

**Comment by JavLuv** [comment]
Added this features in v1.2.3
